=== hmcts/cpp-context-defence/defence-event/defence-event-listener/src/yaml/json/schema/defence.event.add-defence-client-bdf.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/defence/json/schema/event/defence.event.add-defence-client-bdf.json",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "dateOfBirth": {
      "type": "string",
      "format": "date"
    },
    "isVisible": {
      "type": "boolean"
    },
    "idpcDetailsId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "caseId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "defendantId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "isLockedByRepOrder": {
      "type": "boolean"
    },
    "associatedOrganisationId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "organisationName": {
      "type": "string"
    }
  },
  "required": [
    "firstName",
    "lastName",
    "dateOfBirth",
    "isVisible",
    "idpcDetailsId",
    "caseId",
    "defendantId",
    "isLockedByRepOrder"
  ]
}

=== hmcts/cpp-context-defence/defence-command/defence-command-handler/src/raml/json/defence.command.add-defence-client-record-bdf.json
{
  "firstName": "test first name",
  "lastName": "test last name",
  "dateOfBirth": "1992-01-01",
  "isVisible": true,
  "idpcDetailsId": "0c9df1fb-7bce-4e33-88dd-db91f75adeb8",
  "caseId": "0c9df1fb-7bce-4e33-88dd-db91f75adeb9",
  "defendantId": "0c9df1fb-7bce-4e33-88dd-db91f75adeb6",
  "isLockedByRepOrder": true,
  "associatedOrganisationId": "0c9df1fb-7bce-4e33-88dd-db91f75adeb2",
  "organisationName": "test organisation name"
}
